-- sql/migrations/rollback/DANGER_033_topic_summaries_tldr.sql
--
-- ┌─────────────────────────────────────────────────────────────────────┐
-- │ DANGER: ROLLBACK MIGRATION                                          │
-- │                                                                     │
-- │ This script DROPs the tldr_one_line + tldr_short columns from      │
-- │ topic_summaries and restores wiki_topic_upsert's pre-033 signature. │
-- │ Any TLDR forms generated by v0.13+ are lost; bodies (`content`)     │
-- │ are preserved.                                                      │
-- │                                                                     │
-- │ Rollback is for development / recovery, not for routine operation. │
-- │ The Python MCP server v0.13.0+ may pass tldr_* params to            │
-- │ wiki_topic_upsert; after this rollback, those calls will hit a     │
-- │ "function does not exist" error. Downgrade the server to v0.12.x   │
-- │ alongside running this script.                                      │
-- │                                                                     │
-- │ To run this intentionally:                                          │
-- │   psql $DATABASE_URL <<'EOF'                                        │
-- │   SET ogham.confirm_rollback = 'I-KNOW-WHAT-I-AM-DOING';           │
-- │   \i sql/migrations/rollback/DANGER_033_topic_summaries_tldr.sql    │
-- │   EOF                                                               │
-- │                                                                     │
-- │ Piping this file naively (psql $URL < this_file) will FAIL by      │
-- │ design -- the session variable is checked before anything else.    │
-- └─────────────────────────────────────────────────────────────────────┘

-- Guard lives INSIDE the transaction so that a missing session variable
-- aborts the whole rollback rather than just the DO block. Pre-033
-- DANGER files put the guard before BEGIN, which means a naive
-- `psql $URL -f file.sql` without ON_ERROR_STOP=1 prints the ERROR
-- and then keeps running the destructive ops below. Putting the guard
-- inside BEGIN makes the abort transactional.

BEGIN;

DO $$
BEGIN
    IF current_setting('ogham.confirm_rollback', true) IS DISTINCT FROM 'I-KNOW-WHAT-I-AM-DOING' THEN
        RAISE EXCEPTION USING
            MESSAGE = 'Rollback refused -- explicit opt-in required.',
            HINT = 'Run "SET ogham.confirm_rollback = ''I-KNOW-WHAT-I-AM-DOING'';" in the same session before this script. See file header for details.';
    END IF;
END$$;

-- ── Restore wiki_topic_upsert to its pre-033 (10-param) signature ────

DROP FUNCTION IF EXISTS wiki_topic_upsert(
    text, text, text, vector, uuid[], text, uuid, bytea, integer, float, text, text
);

CREATE OR REPLACE FUNCTION wiki_topic_upsert(
    p_profile text,
    p_topic_key text,
    p_content text,
    p_embedding vector,
    p_source_memory_ids uuid[],
    p_model_used text,
    p_source_cursor uuid,
    p_source_hash bytea,
    p_token_count integer DEFAULT NULL,
    p_importance float DEFAULT 0.5
)
RETURNS topic_summaries
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, extensions, pg_catalog
AS $$
DECLARE
    upserted topic_summaries;
BEGIN
    INSERT INTO topic_summaries (
        topic_key, profile_id, content, embedding,
        source_count, source_cursor, source_hash,
        token_count, importance, model_used
    )
    VALUES (
        p_topic_key, p_profile, p_content, p_embedding,
        cardinality(p_source_memory_ids), p_source_cursor, p_source_hash,
        p_token_count, p_importance, p_model_used
    )
    ON CONFLICT (profile_id, topic_key) DO UPDATE SET
        content = EXCLUDED.content,
        embedding = EXCLUDED.embedding,
        source_count = EXCLUDED.source_count,
        source_cursor = EXCLUDED.source_cursor,
        source_hash = EXCLUDED.source_hash,
        token_count = EXCLUDED.token_count,
        importance = EXCLUDED.importance,
        model_used = EXCLUDED.model_used,
        version = topic_summaries.version + 1,
        status = 'fresh',
        stale_reason = NULL
    RETURNING * INTO upserted;

    IF upserted.id IS NULL THEN
        RETURN NULL;
    END IF;

    DELETE FROM topic_summary_sources WHERE summary_id = upserted.id;

    INSERT INTO topic_summary_sources (summary_id, memory_id)
    SELECT upserted.id, m.id
      FROM unnest(p_source_memory_ids) AS t(id)
      JOIN memories m ON m.id = t.id
    ON CONFLICT DO NOTHING;

    RETURN upserted;
END;
$$;

-- ── Drop the columns ─────────────────────────────────────────────────

ALTER TABLE topic_summaries
    DROP COLUMN IF EXISTS tldr_one_line,
    DROP COLUMN IF EXISTS tldr_short;

COMMIT;
